### PR TITLE
Update ts3server.ini

### PR DESCRIPTION
**Pull request by xopez**
Hello,
Whitelist and blacklist needed to be renamed for future versions.
Otherwise you get a warning with this:
```
2020-11-16 08:16:15.421211|WARNING |ServerMain    |   |Warning - name 'query_ip_whitelist' from file /home/ts3server/serverfiles/ts3server.ini is deprecated (but understood), please use the new name 'query_ip_allowlist' instead.
2020-11-16 08:16:15.421230|WARNING |ServerMain    |   |Warning - name 'query_ip_blacklist' from file /home/ts3server/serverfiles/ts3server.ini is deprecated (but understood), please use the new name 'query_ip_denylist' instead.
```
Generating a new config file also lets the `voice_ip` and `filetransfer_ip` fields empty. This needs to be tested.
Furthermore enable http query protocols which were introduced in `Server Release 3.12.0 18 March 2020`: https://community.teamspeak.com/t/teamspeak-server-3-12-x/3916
The changelog for the rename: https://community.teamspeak.com/t/teamspeak-server-3-13-x/13301

Also the license should be accepted in the ini. I don't know how the file is placed, but if it's automatically activated we should do it in the ini instead of the local file.

### CODE REVIEW

**Comment by xopez** [comment]
I can confirm new that this configuraion with empty `voice_ip` and `filetransfer_ip` and current LGSM release.

**Comment by xopez** [comment]
If we set in the config that the license is accepted, we can remove this part https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/command_start.sh#L28-L31 since it does the name just with a file and not with config parameter. As I have seen it, there is no question wether the user wants to accept it or not. 

The only difficult part would be for the guys who have the file and the part not in the configfile. The configfile doesn't get overwritten. So we could try to grab it from config and if it's not there, than we can append the file with it.

**Comment by dgibbs64** [comment]
Thanks for looking at this. It is a priority issue to get resolved.

**Comment by dgibbs64** [comment]
Is there a teamspeak command to generate the ini file?

**Comment by xopez** [comment]
> 
> 
> Is there a teamspeak command to generate the ini file?

yes. I generated it on windows with `.\ts3server.exe createinifile=1`. On Linux this should be equivalent., For activating https-query you have to extent the `query_protocols` parameter with the `https`. For https you also have to specify a certfile and a keyfile, otherwise you get a warning in the log and it will still be disabled. So we should let it this way.
The files needs not be specified in the ini by:
```
query_https_certificate_file='certfilepath'
query_https_private_key_file='keyfilepath'
```

**Comment by dgibbs64** [comment]
I tried `createinifile=1` on Linux and it didn't seem to work. I will test again soon 🙂

**Comment by xopez** [comment]
For me this works:
Fresh TeamSpeak installation on Windows Subsystem for Linux:
```
smoser1@EF-50102756-N:~/teamspeak3-server_linux_amd64$ touch .ts3server_license_accepted
smoser1@EF-50102756-N:~/teamspeak3-server_linux_amd64$ ./ts3server createinifile=1
2020-11-20 15:04:00.763459|INFO    |ServerLibPriv |   |TeamSpeak 3 Server 3.13.2 (2020-11-18 11:37:32)
2020-11-20 15:04:00.773354|INFO    |ServerLibPriv |   |SystemInformation: Linux 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 Binary: 64bit
2020-11-20 15:04:00.773720|INFO    |ServerLibPriv |   |Using hardware aes
2020-11-20 15:04:00.783183|INFO    |DatabaseQuery |   |dbPlugin name:    SQLite3 plugin, Version 3, (c)TeamSpeak Systems GmbH
2020-11-20 15:04:00.783822|INFO    |DatabaseQuery |   |dbPlugin version: 3.11.1
2020-11-20 15:04:00.785239|INFO    |DatabaseQuery |   |checking database integrity (may take a while)
2020-11-20 15:04:00.813404|INFO    |SQL           |   |db_CreateTables() tables created

------------------------------------------------------------------
                      I M P O R T A N T
------------------------------------------------------------------
               Server Query Admin Account created
         loginname= "serveradmin", password= "RdXoZQno"
         apikey= "BAD2XiVS2NHurqmcrIMb-ISxrx5PEN-n9VZKNUv"
------------------------------------------------------------------

2020-11-20 15:04:00.929526|WARNING |Accounting    |   |Unable to open licensekey.dat, falling back to limited functionality
2020-11-20 15:04:00.937126|INFO    |Accounting    |   |Licensing Information
2020-11-20 15:04:00.937435|INFO    |Accounting    |   |licensed to       : Anonymous
2020-11-20 15:04:00.939584|INFO    |Accounting    |   |type              : No License
2020-11-20 15:04:00.940102|INFO    |Accounting    |   |starting date     : Thu Oct  1 00:00:00 2020
2020-11-20 15:04:00.940626|INFO    |Accounting    |   |ending date       : Tue Nov  1 00:00:00 2022
2020-11-20 15:04:00.941188|INFO    |Accounting    |   |max virtualservers: 1
2020-11-20 15:04:00.941719|INFO    |Accounting    |   |max slots         : 32
2020-11-20 15:04:01.452064|INFO    |              |   |Puzzle precompute time: 486
2020-11-20 15:04:01.459480|INFO    |FileManager   |   |listening on 0.0.0.0:30033, [::]:30033
2020-11-20 15:04:01.460756|INFO    |VirtualSvrMgr |   |executing monthly interval
2020-11-20 15:04:01.466213|INFO    |VirtualSvrMgr |   |reset virtualserver traffic statistics
2020-11-20 15:04:01.527327|INFO    |Query         |   |Using a query thread pool size of 2
2020-11-20 15:04:01.645550|INFO    |VirtualServerBase|1  |listening on 0.0.0.0:9987, [::]:9987
2020-11-20 15:04:01.647450|WARNING |VirtualServer |1  |--------------------------------------------------------
2020-11-20 15:04:01.647727|WARNING |VirtualServer |1  |ServerAdmin privilege key created, please use the line below
2020-11-20 15:04:01.648314|WARNING |VirtualServer |1  |token=ZBQA0JTjj18RifmRvfNtLbyKWyAfULDJyl882Tx7
2020-11-20 15:04:01.649054|WARNING |VirtualServer |1  |--------------------------------------------------------

------------------------------------------------------------------
                      I M P O R T A N T
------------------------------------------------------------------
      ServerAdmin privilege key created, please use it to gain
      serveradmin rights for your virtualserver. please
      also check the doc/privilegekey_guide.txt for details.

       token=ZBQA0JTjj18RifmRvfNtLbyKWyAfULDJyl882Tx7
------------------------------------------------------------------

2020-11-20 15:04:01.656863|INFO    |Query         |   |listening for query on 0.0.0.0:10011, [::]:10011
2020-11-20 15:04:01.657710|INFO    |              |   |creating QUERY_SSH_RSA_HOST_KEY file: ssh_host_rsa_key
2020-11-20 15:04:01.944423|INFO    |              |   |myTeamSpeak identifier revocation list was downloaded successfully - all related features are activated
2020-11-20 15:04:02.762511|INFO    |Query         |   |listening for ssh query on 0.0.0.0:10022, [::]:10022
2020-11-20 15:04:02.763056|INFO    |Query         |   |listening for http query on 0.0.0.0:10080, [::]:10080
2020-11-20 15:04:02.769518|INFO    |CIDRManager   |   |updated query_ip_allowlist ips: 127.0.0.1/32, ::1/128,
^C2020-11-20 15:04:07.159243|INFO    |ServerMain    |   |Received signal SIGINT, shutting down.
2020-11-20 15:04:07.160898|INFO    |VirtualServerBase|1  |stopped
smoser1@EF-50102756-N:~/teamspeak3-server_linux_amd64$ ls
CHANGELOG  doc    libts3_ssh.so        libts3db_postgresql.so  logs                    query_ip_denylist.txt  serverquerydocs  ssh_host_rsa_key  ts3server.ini       ts3server_minimal_runscript.sh  tsdns
LICENSE    files  libts3db_mariadb.so  libts3db_sqlite3.so     query_ip_allowlist.txt  redist                 sql              ts3server         ts3server.sqlitedb  ts3server_startscript.sh
smoser1@EF-50102756-N:~/teamspeak3-server_linux_amd64$ ls | grep ts3server
ts3server
ts3server.ini
ts3server.sqlitedb
ts3server_minimal_runscript.sh
ts3server_startscript.sh
smoser1@EF-50102756-N:~/teamspeak3-server_linux_amd64$
```

**Comment by dgibbs64** [comment]
Got this working. I think I am going to re-work config installation for ts3server. Using `./ts3server createinifile=1` to generate the file on install. However for now this updated ini file will do great

**Pull request merged**
