### PR TITLE
fix(armar): adapts config to the new specification

### PR DESCRIPTION
**Pull request by Marcin648**
New config following specification on https://community.bistudio.com/wiki/Arma_Reforger:Server_Hosting

### CODE REVIEW

**Comment by Marcin648** [comment]
Delayed.
New `a2s` variables not working for some reason. Waiting for game developers feedback.

**Comment by Marcin648** [comment]
Arma Reforger devs had some merge issue, so new a2s settings should be available in next release. 

Official documentation changelog:
https://community.bistudio.com/wiki?title=Arma_Reforger:Server_Hosting&diff=prev&oldid=341653

For now, legacy a2sQueryEnabled + steamQueryPort works fine, but should be changed after next release.

**Comment by Marcin648** [comment]
`a2sQueryEnabled` and `steamQueryPort` were removed in newest Arma Reforger release.
But `a2s` working now :)

**Comment by dgibbs64** [comment]
I will get this out as soon as I can :)

**Review by dgibbs64 — APPROVED** [review]

**Pull request merged**
